# Generated by Django 4.2.20 on 2025-03-29 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.voiture')),
            ],
        ),
    ]
