# Generated by Django 4.2.20 on 2025-03-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trajet_owner_id_trajet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='active', max_length=10),
        ),
    ]
