# Generated by Django 4.2.20 on 2025-05-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_trajet_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
